"use strict";
const Permission = {
  ADMINISTRATOR: "ADMINISTRATOR",
  PANEL_ACCESS: "PANEL_ACCESS",

  VIEW_ROLE: "VIEW_ROLE",
  CREATE_ROLE: "CREATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  ADD_ROLE: "ADD_ROLE",
  REMOVE_ROLE: "REMOVE_ROLE",
  EDIT_ROLE: "EDIT_ROLE",
  REMOVE_PERM: "REMOVE_PERM",

  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPLOAD_IMG: "UPLOAD_IMG",
  VIEW_CATEGORY: "VIEW_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  ADD_SUB_CATEGORY: "ADD_SUB_CATEGORY",
  DELETE_SUB_CATEGORY: "DELETE_SUB_CATEGORY",
};

module.exports = Permission;
